# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: Z7uG-mxM
    url: /
    weight: 10
  - name: Blog
    identifier: VzMd9brw
    url: /#blog
    weight: 20
  - name: Papers
    identifier: Ij20gvVA
    url: /#papers
    weight: 30
  - name: Projects
    identifier: UPBJgD8y
    url: projects/
    weight: 40
